export interface Scheme {
  id: string;
  name_ta: string;
  name_en: string;
  link: string;
  category: string;
  eligibility_ta: string;
  eligibility_en: string;
  benefits_ta: string;
  benefits_en: string;
  documents_ta: string[];
  documents_en: string[];
  how_to_apply_ta: string;
  how_to_apply_en: string;
  estimated_savings_ta: string;
  estimated_savings_en: string;
  icon: string;
  color: string;
  eligibilityCheck?: (member: { age: number; income?: number; gender?: string; occupation?: string }) => boolean;
}

export const schemes: Scheme[] = [
  {
    id: 'cm_health',
    name_ta: 'முதலமைச்சரின் விரிவான மருத்துவக் காப்பீட்டுத் திட்டம்',
    name_en: 'CM Comprehensive Health Insurance Scheme',
    link: 'https://www.cmchistn.com/',
    category: 'health',
    eligibility_ta: 'ஆண்டு வருமானம் ₹1,20,000-க்குக் குறைவான குடும்பங்கள்',
    eligibility_en: 'Families with annual income below ₹1,20,000',
    benefits_ta: '₹5 லட்சம் வரை இலவச மருத்துவ சிகிச்சை, 1000+ சிகிச்சைகள் உள்ளடக்கம்',
    benefits_en: 'Free medical treatment up to ₹5 lakhs, covers 1000+ procedures',
    documents_ta: ['ஆதார் அட்டை', 'வருமானச் சான்றிதழ்', 'குடும்ப அட்டை', 'புகைப்படம்'],
    documents_en: ['Aadhaar Card', 'Income Certificate', 'Ration Card', 'Photograph'],
    how_to_apply_ta: 'அருகிலுள்ள அரசு மருத்துவமனையில் CMCHIS மையத்தில் பதிவு செய்யுங்கள்',
    how_to_apply_en: 'Register at the CMCHIS counter in nearest government hospital',
    estimated_savings_ta: 'ஆண்டுக்கு ₹50,000 - ₹5,00,000 மருத்துவ செலவு சேமிப்பு',
    estimated_savings_en: '₹50,000 - ₹5,00,000 medical expense savings per year',
    icon: 'medkit',
    color: '#DC2626',
    eligibilityCheck: (m) => (m.income ?? 0) <= 120000,
  },
  {
    id: 'first_graduate',
    name_ta: 'முதல் பட்டதாரி திட்டம்',
    name_en: 'First Graduate Scheme',
    link: 'https://www.tnscholarships.gov.in/',
    category: 'education',
    eligibility_ta: 'குடும்பத்தில் முதல் பட்டதாரி மாணவர்கள், ஆண்டு வருமானம் ₹2.5 லட்சத்திற்கு குறைவு',
    eligibility_en: 'First graduate students in family, annual income below ₹2.5 lakhs',
    benefits_ta: 'கல்வி கட்டணம் இலவசம், மாதாந்திர உதவித்தொகை',
    benefits_en: 'Free tuition fees and monthly stipend',
    documents_ta: ['மாணவர் ஆதார்', 'பெற்றோர் வருமானச் சான்று', 'சேர்க்கை சான்று', 'முதல் பட்டதாரி சான்று'],
    documents_en: ['Student Aadhaar', 'Parent Income Certificate', 'Admission Proof', 'First Graduate Certificate'],
    how_to_apply_ta: 'கல்லூரியில் சேரும்போது விண்ணப்பிக்கவும்',
    how_to_apply_en: 'Apply at the time of college admission',
    estimated_savings_ta: 'ஆண்டுக்கு ₹25,000 - ₹1,00,000 கல்வி செலவு சேமிப்பு',
    estimated_savings_en: '₹25,000 - ₹1,00,000 education cost savings per year',
    icon: 'school',
    color: '#3B82F6',
    eligibilityCheck: (m) => (m.occupation === 'student') && (m.income ?? 0) <= 250000,
  },
  {
    id: 'post_matric',
    name_ta: 'பிற்படுத்தப்பட்டோர் மேல்நிலைக் கல்வி உதவித்தொகை',
    name_en: 'Post-Matric Scholarship (BC/MBC)',
    link: 'https://bcmbc.tn.gov.in/scholarship',
    category: 'education',
    eligibility_ta: 'பிற்படுத்தப்பட்ட வகுப்பு மாணவர்கள், 10ஆம் வகுப்பு முடித்தவர்கள்',
    eligibility_en: 'BC/MBC students who completed 10th standard',
    benefits_ta: 'கல்வி கட்டணம் + மாதாந்திர உதவித்தொகை + விடுதி கட்டணம்',
    benefits_en: 'Tuition fees + monthly stipend + hostel charges',
    documents_ta: ['ஆதார் அட்டை', 'சாதிச் சான்றிதழ்', 'வருமானச் சான்றிதழ்', 'மதிப்பெண் சான்று'],
    documents_en: ['Aadhaar Card', 'Community Certificate', 'Income Certificate', 'Mark Sheet'],
    how_to_apply_ta: 'தமிழ்நாடு e-சேவை இணையதளத்தில் ஆன்லைனில் விண்ணப்பிக்கவும்',
    how_to_apply_en: 'Apply online through Tamil Nadu e-Sevai website',
    estimated_savings_ta: 'ஆண்டுக்கு ₹15,000 - ₹50,000',
    estimated_savings_en: '₹15,000 - ₹50,000 per year',
    icon: 'book',
    color: '#8B5CF6',
    eligibilityCheck: (m) => m.occupation === 'student',
  },
  {
    id: 'moovalur',
    name_ta: 'மூவலூர் ராமாமிர்தம் அம்மையார் திட்டம்',
    name_en: 'Moovalur Ramamirtham Ammaiyar Scheme',
    link: 'https://www.pudumaipenn.tn.gov.in/',
    category: 'women',
    eligibility_ta: 'ஏழை குடும்பங்களின் பெண் குழந்தைகள், 12ஆம் வகுப்பு வரை படிக்கும் மாணவிகள்',
    eligibility_en: 'Girl children from poor families studying up to 12th standard',
    benefits_ta: '₹25,000 கல்வி உதவி (12ஆம் வகுப்பு முடித்தவுடன்)',
    benefits_en: '₹25,000 educational assistance upon completing 12th standard',
    documents_ta: ['ஆதார் அட்டை', 'பள்ளிச் சான்றிதழ்', 'வங்கிக் கணக்கு', 'வருமானச் சான்றிதழ்'],
    documents_en: ['Aadhaar Card', 'School Certificate', 'Bank Account', 'Income Certificate'],
    how_to_apply_ta: 'பள்ளி மூலமாக விண்ணப்பிக்கவும்',
    how_to_apply_en: 'Apply through school',
    estimated_savings_ta: '₹25,000 ஒரு முறை பலன்',
    estimated_savings_en: '₹25,000 one-time benefit',
    icon: 'woman',
    color: '#EC4899',
    eligibilityCheck: (m) => m.gender === 'female' && m.age >= 16 && m.age <= 20,
  },
  {
    id: 'mahalir_urimai',
    name_ta: 'மகளிர் உரிமைத் தொகை திட்டம்',
    name_en: 'Mahalir Urimai Thogai (Kalaignar)',
    link: 'https://kmut.tn.gov.in/',
    category: 'women',
    eligibility_ta: '21 வயதுக்கு மேற்பட்ட பெண்கள், குடும்ப ஆண்டு வருமானம் ₹2.5 லட்சத்திற்கு குறைவு',
    eligibility_en: 'Women above 21 years, family annual income below ₹2.5 lakhs',
    benefits_ta: 'மாதம் ₹1,000 நேரடியாக வங்கிக் கணக்கில்',
    benefits_en: '₹1,000 per month directly to bank account',
    documents_ta: ['ஆதார் அட்டை', 'குடும்ப அட்டை', 'வங்கிக் கணக்கு', 'வருமானச் சான்றிதழ்'],
    documents_en: ['Aadhaar Card', 'Ration Card', 'Bank Account', 'Income Certificate'],
    how_to_apply_ta: 'அருகிலுள்ள கிராம நிர்வாக அலுவலகத்தில் விண்ணப்பிக்கவும்',
    how_to_apply_en: 'Apply at nearest Village Administrative Office',
    estimated_savings_ta: 'ஆண்டுக்கு ₹12,000',
    estimated_savings_en: '₹12,000 per year',
    icon: 'people',
    color: '#F59E0B',
    eligibilityCheck: (m) => m.gender === 'female' && m.age >= 21 && (m.income ?? 0) <= 250000,
  },
  {
    id: 'muthulakshmi',
    name_ta: 'டாக்டர் முத்துலட்சுமி ரெட்டி மகப்பேறு நிதி உதவித் திட்டம்',
    name_en: 'Dr. Muthulakshmi Reddy Maternity Scheme',
    link: 'https://nhm.tn.gov.in/en/rchs/maternal-health',
    category: 'women',
    eligibility_ta: 'ஏழை குடும்பங்களின் கர்ப்பிணிப் பெண்கள்',
    eligibility_en: 'Pregnant women from economically weaker families',
    benefits_ta: '₹18,000 மகப்பேறு நிதி உதவி (முதல் 2 குழந்தைகளுக்கு)',
    benefits_en: '₹18,000 maternity assistance (for first 2 children)',
    documents_ta: ['ஆதார் அட்டை', 'மருத்துவச் சான்றிதழ்', 'வருமானச் சான்றிதழ்', 'வங்கிக் கணக்கு'],
    documents_en: ['Aadhaar Card', 'Medical Certificate', 'Income Certificate', 'Bank Account'],
    how_to_apply_ta: 'அருகிலுள்ள அரசு மருத்துவமனையில் பதிவு செய்யுங்கள்',
    how_to_apply_en: 'Register at nearest government hospital',
    estimated_savings_ta: '₹18,000 ஒவ்வொரு பிரசவத்திற்கும்',
    estimated_savings_en: '₹18,000 per delivery',
    icon: 'heart',
    color: '#EF4444',
    eligibilityCheck: (m) => m.gender === 'female' && m.age >= 18 && m.age <= 45,
  },
  {
    id: 'marriage_assistance',
    name_ta: 'திருமண உதவித் திட்டம்',
    name_en: 'Marriage Assistance Scheme',
    link: 'https://www.socialjustice.tn.gov.in/',
    category: 'women',
    eligibility_ta: 'ஏழை குடும்பங்களின் பெண்கள், பட்டப்படிப்பு முடித்தவர்கள்',
    eligibility_en: 'Women from poor families who completed degree',
    benefits_ta: '₹50,000 திருமண உதவி + ₹25,000 கல்வி ஊக்கத்தொகை',
    benefits_en: '₹50,000 marriage assistance + ₹25,000 education incentive',
    documents_ta: ['ஆதார் அட்டை', 'பட்டச் சான்றிதழ்', 'வருமானச் சான்றிதழ்', 'திருமண அழைப்பிதழ்'],
    documents_en: ['Aadhaar Card', 'Degree Certificate', 'Income Certificate', 'Marriage Invitation'],
    how_to_apply_ta: 'மாவட்ட சமூக நலத்துறையில் விண்ணப்பிக்கவும்',
    how_to_apply_en: 'Apply at District Social Welfare Office',
    estimated_savings_ta: '₹50,000 - ₹75,000 ஒரு முறை',
    estimated_savings_en: '₹50,000 - ₹75,000 one-time',
    icon: 'gift',
    color: '#D946EF',
    eligibilityCheck: (m) => m.gender === 'female' && m.age >= 18,
  },
  {
    id: 'farmer_insurance',
    name_ta: 'பிரதமர் பயிர் காப்பீட்டுத் திட்டம்',
    name_en: 'PM Fasal Bima Yojana',
    link: 'https://pmfby.gov.in/',
    category: 'farmer',
    eligibility_ta: 'அனைத்து விவசாயிகளும் (நிலம் உள்ள/குத்தகை)',
    eligibility_en: 'All farmers (own land or leased)',
    benefits_ta: 'பயிர் சேதத்திற்கு முழு காப்பீடு, குறைந்த பிரீமியம் (1.5% - 5%)',
    benefits_en: 'Full crop damage insurance, low premium (1.5% - 5%)',
    documents_ta: ['ஆதார் அட்டை', 'நில ஆவணங்கள்', 'வங்கிக் கணக்கு', 'பட்டா/குத்தகை ஒப்பந்தம்'],
    documents_en: ['Aadhaar Card', 'Land Documents', 'Bank Account', 'Patta/Lease Agreement'],
    how_to_apply_ta: 'அருகிலுள்ள வங்கி அல்லது CSC மையத்தில் விண்ணப்பிக்கவும்',
    how_to_apply_en: 'Apply at nearest bank or CSC center',
    estimated_savings_ta: 'பயிர் சேதத்தின்போது ₹25,000 - ₹2,00,000',
    estimated_savings_en: '₹25,000 - ₹2,00,000 during crop damage',
    icon: 'leaf',
    color: '#22C55E',
    eligibilityCheck: (m) => m.occupation === 'farmer',
  },
  {
    id: 'farmer_pension',
    name_ta: 'பிரதமர் கிசான் மான்-தன் திட்டம்',
    name_en: 'PM Kisan Maan-Dhan',
    link: 'https://maandhan.in/',
    category: 'farmer',
    eligibility_ta: '18-40 வயது விவசாயிகள், 2 ஹெக்டேருக்கு குறைவான நிலம்',
    eligibility_en: 'Farmers aged 18-40, less than 2 hectares land',
    benefits_ta: '60 வயதிற்கு பிறகு மாதம் ₹3,000 ஓய்வூதியம்',
    benefits_en: '₹3,000 monthly pension after age 60',
    documents_ta: ['ஆதார் அட்டை', 'நில ஆவணங்கள்', 'வங்கிக் கணக்கு'],
    documents_en: ['Aadhaar Card', 'Land Documents', 'Bank Account'],
    how_to_apply_ta: 'CSC மையம் அல்லது PM-Kisan போர்ட்டலில் பதிவு',
    how_to_apply_en: 'Register at CSC center or PM-Kisan portal',
    estimated_savings_ta: '60 வயதிற்குப் பிறகு ஆண்டுக்கு ₹36,000',
    estimated_savings_en: '₹36,000 per year after age 60',
    icon: 'sunny',
    color: '#F97316',
    eligibilityCheck: (m) => m.occupation === 'farmer' && m.age >= 18 && m.age <= 40,
  },
  {
    id: 'old_age_pension',
    name_ta: 'முதியோர் ஓய்வூதியத் திட்டம்',
    name_en: 'Old Age Pension Scheme',
    link: 'https://nsap.nic.in/',
    category: 'senior',
    eligibility_ta: '60 வயதுக்கு மேற்பட்டவர்கள், ஆண்டு வருமானம் ₹24,000-க்கு குறைவு',
    eligibility_en: 'Persons above 60 years, annual income below ₹24,000',
    benefits_ta: 'மாதம் ₹1,000 ஓய்வூதியம்',
    benefits_en: '₹1,000 monthly pension',
    documents_ta: ['ஆதார் அட்டை', 'வயது சான்றிதழ்', 'வருமானச் சான்றிதழ்', 'வங்கிக் கணக்கு'],
    documents_en: ['Aadhaar Card', 'Age Certificate', 'Income Certificate', 'Bank Account'],
    how_to_apply_ta: 'கிராம நிர்வாக அலுவலகத்தில் விண்ணப்பிக்கவும்',
    how_to_apply_en: 'Apply at Village Administrative Office',
    estimated_savings_ta: 'ஆண்டுக்கு ₹12,000',
    estimated_savings_en: '₹12,000 per year',
    icon: 'person',
    color: '#6366F1',
    eligibilityCheck: (m) => m.age >= 60 && (m.income ?? 0) <= 24000,
  },
  {
    id: 'sukanya',
    name_ta: 'சுகன்யா சம்ரிதி யோஜனா',
    name_en: 'Sukanya Samriddhi Yojana',
    link: 'https://www.nsiindia.gov.in/',
    category: 'savings',
    eligibility_ta: '10 வயதுக்குக் குறைவான பெண் குழந்தைகள் (அதிகபட்சம் 2 குழந்தைகள்)',
    eligibility_en: 'Girl children below 10 years (maximum 2 children)',
    benefits_ta: '8.2% வட்டி விகிதம், வரி சலுகை, 21 ஆண்டுகளில் முதிர்வு',
    benefits_en: '8.2% interest rate, tax benefits, matures in 21 years',
    documents_ta: ['குழந்தையின் பிறப்புச் சான்றிதழ்', 'பெற்றோர் ஆதார்', 'முகவரி சான்று'],
    documents_en: ['Child Birth Certificate', 'Parent Aadhaar', 'Address Proof'],
    how_to_apply_ta: 'அருகிலுள்ள தபால் நிலையம் அல்லது வங்கியில் கணக்கு துவக்கவும்',
    how_to_apply_en: 'Open account at nearest post office or bank',
    estimated_savings_ta: '₹1,000/மாதம் முதலீடு → 21 ஆண்டுகளில் ~₹5.5 லட்சம்',
    estimated_savings_en: '₹1,000/month investment → ~₹5.5 lakhs in 21 years',
    icon: 'star',
    color: '#EC4899',
    eligibilityCheck: (m) => m.gender === 'female' && m.age < 10,
  },
  {
    id: 'senior_savings',
    name_ta: 'மூத்த குடிமக்கள் சேமிப்புத் திட்டம்',
    name_en: 'Senior Citizen Savings Scheme',
    link: 'https://www.nsiindia.gov.in/',
    category: 'senior',
    eligibility_ta: '60 வயதுக்கு மேற்பட்டவர்கள்',
    eligibility_en: 'Persons above 60 years',
    benefits_ta: '8.2% வட்டி விகிதம், ₹30 லட்சம் வரை முதலீடு, காலாண்டு வட்டி',
    benefits_en: '8.2% interest rate, invest up to ₹30 lakhs, quarterly interest payout',
    documents_ta: ['ஆதார் அட்டை', 'வயது சான்றிதழ்', 'PAN அட்டை', 'புகைப்படம்'],
    documents_en: ['Aadhaar Card', 'Age Certificate', 'PAN Card', 'Photograph'],
    how_to_apply_ta: 'அருகிலுள்ள தபால் நிலையம் அல்லது வங்கியில் கணக்கு துவக்கவும்',
    how_to_apply_en: 'Open account at nearest post office or bank',
    estimated_savings_ta: '₹10 லட்சம் முதலீடு → ஆண்டுக்கு ₹82,000 வட்டி',
    estimated_savings_en: '₹10 lakh investment → ₹82,000 interest per year',
    icon: 'shield-checkmark',
    color: '#0EA5E9',
    eligibilityCheck: (m) => m.age >= 60,
  },
];
